ArquivoRelatoriu/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	#informasaun baluns sobre gias
	path('upload/', upload_pdf, name='upload_pdf'),
	path('pdfs/lista/informasaun/lei nu 2/2025/ 22 de janeru', pdf_list, name='pdf_list'),

    #lista funsionnariu
	path('lista/Funsionariu', funsionario_list, name="lista-funsionariu"),
	path('Adisiona/Finsionariu', funsionario_create, name='adisiona-funsionariu'),
	path('funsionario/<int:pk>/update/', funsionario_update, name='funsionario_update'),
	path('delete/<int:id>/Funsionariu/', delete_Funsionariu, name='delete_Funsionariu'),

	# path('phone-info-Public/<int:phone_info_id>/', phone_detail_viewPublic, name='phone_detail_viewPublic'),
	path('lista/arqiuvu', relatoriu_list, name="Lista-Arquivu"),
	path('Adisiona/arqiuvu', Arquivu_create, name="Adisiona-Arquivu"),
	path('Update/<str:pk>/arqiuvu', ArquivuRelatoriu_update, name="update-Arquivu"),
	path('delete/<int:id>/', delete_arquivu_relatoriu, name='delete_arquivu_relatoriu'),
	path('detail/arquivu/<int:pk>/report', detail_ArquivuRelatoriu, name='detail_ArquivuRelatoriu'),


	path('Lista/karta-entrada',kartaEntrasa_list, name="kartaEntrasa_list"),
	path('Adisiona/karta-entrada',Entrada_create, name="Entrada_create"),
	path('mark_as_read/<int:pk>/', mark_as_read, name='mark_as_read'),
	path('update/karta/entrada/<int:pk>/', update_karta_entrada, name='update_karta_entrada'),
	path('detail/karta_entrada/<int:pk>/', detail_karta_entrada, name='detail_karta_entrada'),


	path('Klinika/MapaKlinika/Lista ', MapaKlinika_list, name='MapaKlinika_list'),
	path('Add/klinik/', add_klinik, name='add_klinik'),
	path('mapaklinik/<int:pk>/', MapaKlinikDetailView, name='mapaklinik_detail'),
    	path('mapaklinik/<int:klinika_id>/add_cliente_raipoint/', add_cliente_raipoint, name='add_cliente_raipoint'),
    	path('update-cliente-raipoint/<int:point_id>/', update_cliente_raipoint, name='update_cliente_raipoint'),


	]

GIAS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from GIAS import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('publicApp.urls')),
    path('', include('main.urls')),
    path('utilizador/', include('users.urls')),
    path('Report/', include('report.urls')),
    path('ArquivoR/', include('ArquivoRelatoriu.urls')),
    path('login/', views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(template_name='auth/logout.html'), name='logout'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('dadus-custom/', include('custom.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ArquivoRelatoriu/models.py
from django.db import models
from custom.models import *
# from django.contrib.gis.db import models as gis_models

# from django.contrib.gis.db import models
class PDFUpload(models.Model):
    title = models.CharField(max_length=255)
    file = models.FileField(upload_to='pdfs/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Diresaun(models.Model):
    name = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.name


class Departamentu(models.Model):
    name = models.CharField(max_length=100, unique=True)
  
    def __str__(self): 
        return self.name 
from django.db import models

class ArquivuRelatoriu(models.Model):
    no_carta = models.CharField(max_length=50)
    data_Arquivu = models.DateField()
    departamento = models.ForeignKey(Departamentu, on_delete=models.CASCADE, null=True, blank=True)
    titulo = models.CharField(max_length=500)
    hato_o_ba = models.CharField(max_length=1000, null=True)
    
    # Field baru untuk upload file PDF
    documento_pdf = models.FileField(upload_to='arquivu_relatoriu_pdfs/', )

    def __str__(self):
        return self.titulo



class Funsionario(models.Model):
    nome = models.CharField(max_length=255)
    sexu = models.CharField( max_length=50, 
        choices=[
            ('Mane', 'Mane'),
            ('Feto', 'Feto'),
        ], 
        default='Mane'
    )
    cargo = models.CharField(max_length=100)
    regime = models.CharField( max_length=50, 
        choices=[
            ('Geral', 'Geral'),
            ('Espesial', 'Espesial'),
        ], 
        default='Geral'
    )
    grau = models.CharField( max_length=50, 
        choices=[
            ('A', 'A'),
            ('B', 'B'),
            ('C', 'C'),
            ('D', 'D'),
            ('E', 'E'),
            ('F', 'F'),
        ], 
        default='A'
    )
    level = models.CharField( max_length=50, 
        choices=[
            ('I', 'I'),
            ('II', 'II'),
            ('III', 'III'),
            ('IV', 'IV'),
            ('V', 'V'),
            ('VI', 'VI'),
        ], 
        default='I'
    )
    background = models.CharField(max_length=100, null=True,blank=True)
    scalaun = models.CharField(max_length=100, null=True,blank=True)
    diresaun = models.ForeignKey(Diresaun, on_delete=models.CASCADE,null=True, blank=True)
    departamentu = models.ForeignKey(Departamentu, on_delete=models.CASCADE,null=True, blank=True)
    endereco = models.CharField(max_length=255, blank=True, null=True)
    telefone = models.CharField(max_length=20, blank=True, null=True)
    data_entrada = models.DateField()
    image = models.ImageField(upload_to='Funsionariu/', null=True, blank=True)
    status = models.CharField(max_length=50, choices=[('Active', 'Active'),('Leave', 'Leave'),
            ('Dismissed', 'Dismissed'),
        ],   
        default='Active'
    )
    
    status_profisaun = models.CharField( max_length=50, 
        choices=[
            ('Kontratadu', 'Kontratadu'),
            ('Permanente', 'Permanente'),
        ], 
        default='Permanente'
    )

    def __str__(self):
        return f"{self.nome} - {self.cargo}"

    class Meta:
        ordering = ['nome']



class KartaEntrada(models.Model):
    remetente = models.CharField(max_length=50, )
    destinatário = models.CharField(max_length=50,)
    no_karta = models.CharField(max_length=50, unique=True)
    data_entrada = models.DateField()
    data_dok = models.DateField()
    no_referensia = models.CharField(max_length=50, blank=True, null=True)
    assunto = models.CharField(max_length=255)
    hato_o_ba = models.CharField(max_length=255)
    husi = models.CharField(max_length=255)
    dokumen = models.FileField(upload_to='Arquivu/KartaSaida/', blank=True, null=True)
    despaixa=models.CharField(max_length=800,blank=True, null=True,)
    is_read=models.BooleanField(default=False,null=True, blank=True)
    def __str__(self):
        return f"Karta Entrada {self.no_karta} - {self.assunto}"

    class Meta:
        ordering = ['-data_entrada']


class KartaSaida(models.Model):
    no_karta = models.CharField(max_length=50, unique=True)
    data_saida = models.DateField()
    data_dok = models.DateField()
    no_referensia = models.CharField(max_length=50, blank=True, null=True)
    assunto = models.CharField(max_length=255)
    hato_o_ba = models.CharField(max_length=255)
    husi = models.CharField(max_length=255) 

    def __str__(self):
        return f"Karta Saida {self.no_karta} - {self.assunto}"

    class Meta:
        ordering = ['-data_saida']



class MapaKlinik(models.Model):
    TIPO_KLINIK = [
        ('Privadu', 'Privadu'),
        ('Publiku', 'Publiku'),
    ]

    naran_klinik = models.CharField(max_length=255, unique=True)
    tipo_klinik = models.CharField(max_length=50, choices=TIPO_KLINIK)
    telefone = models.CharField(max_length=20, blank=True, null=True)
    email = models.EmailField(blank=True, null=True)
    responsavel = models.CharField(max_length=255, blank=True, null=True)
    aldeia = models.ForeignKey(Aldeia, on_delete=models.CASCADE,null=True,blank=True)
    village = models.ForeignKey(Village, on_delete=models.CASCADE,null=True,blank=True, related_name="VVillage")
    administrativepost = models.ForeignKey(AdministrativePost, on_delete=models.CASCADE,null=True,blank=True, related_name="AAdministrativePost")
    municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE,null=True,blank=True,related_name="MMunicipality")
    # lokasi = models.PointField(geography=True, blank=True, null=True)  # Koordinat (longitude, latitude)
    # image = models.ImageField(upload_to='MapaKlinik/', null=True, blank=True)
    data_registu = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.naran_klinik} - {self.municipality}"

    class Meta:
        ordering = ['naran_klinik']
        verbose_name = 'Mapa Klinik'
        verbose_name_plural = 'Mapa Klinik'

class ClienteRaiPoint(models.Model):
    klinika = models.ForeignKey(MapaKlinik, on_delete=models.CASCADE, related_name="clinikLocation")
    latitude = models.CharField(max_length=20, null=True, )
    longitude = models.CharField(max_length=20, null=True,)
    image = models.ImageField(upload_to='MapaKlinik/', null=True, blank=True)

    def __str__(self):
        return f"{self.klinika.naran_klinik} - ({self.latitude}, {self.longitude})"

ArquivoRelatoriu/templates/funsionari.html
{% extends "main/layout.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<section>
    <div class="container-fluid">
        <!-- Page Header-->
        <header>
            <ol class="breadcrumb mb-1 mt-1">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Varanda</a></li>
                <li class="breadcrumb-item"><a href="">Lista Departamento</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
            </ol>
        </header>
        {% if messages %}
                        {% for message in messages %} 
                            <div id="divmessage" class="alert alert-{{ message.tags }} alert-dismissable">
                              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                              {{message}}
                            </div>
                        {% endfor %}
                    {% endif %}   

        <div class="row">
            {% if page == "list" %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header d-flex justify-content-end text-center">
                        <div class="text-center border">
                            <a href="{% url 'adisiona-funsionariu'%}" class="btn btn-sm btn-info" title="Add Data">Add <i class="fa fa-plus-square"></i></a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="example" class="table table-hover table-striped w-100">
                                <thead>
                                    <tr>
                                        <th> No</th>
                                        <th> Img </th>
                                        <th>Nome</th>
                                        <th>Cargo</th>
                                        <th>Sexo</th>
                                        <th>Departamento</th>
                                        <th>Data Entrada</th>
                                        <th>Status</th>
                                        <th>Status Profisaun</th>
                                        <th>Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for funsionario in funsionarios %}
                                    <tr>
                                        <td scope="row"> {{forloop.counter}} </td>
                                         <td class="text-center">{% if funsionario.image %}<a href="{{funsionario.image.url}}" target="_blank"><img src="{{funsionario.image.url}}" width="50px" height="50px"></a>{%else%}{%endif%}</td>
                                        <td>{{ funsionario.nome }}</td>
                                        <td>{{ funsionario.cargo }}</td>
                                        <td>{{ funsionario.get_sexu_display }}</td>
                                        <td>{{ funsionario.departamentu }}</td>
                                        <td>{{ funsionario.data_entrada }}</td>
                                        <td>{{ funsionario.get_status_display }}</td>
                                        <td>{{ funsionario.get_status_profisaun_display }}</td>
                                        <td>
                                            <div class="d-flex">
                                                <div class="flex-fill">
                                                    <a href="{% url 'funsionario_update' funsionario.id %}" class="btn btn-sm btn-primary" title="Update"><i class="fa fa-pencil"></i></a>
                                                </div>
                                                <div class="flex-fill">
                                                    <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete-{{ funsionario.id }}" style="text-decoration: none"><i class="fa fa-trash"></i></button>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>

                                    <!-- Modal Delete -->
                                    <div class="modal fade" id="delete-{{ funsionario.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="deleteLabel">Delete Funsionario</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    Ita Boot fiar atu hamos funsionario ne'e: {{ funsionario.nome }}?
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                                                    <a href="{% url 'delete_Funsionariu' funsionario.id %}" class="btn btn-danger">Yes</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}

            {% if page == "form" %}
            <div class="container-fluid pt-5">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <h2><p>Formulariu Adisiona Funsionariu</p></h2>
                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {% crispy form %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function () {
        var table = $('#example').removeAttr('width').DataTable();
    });
    
</script>
<script type="text/javascript">
    function myFunction() {
        var file = document.getElementById("id_image").files[0];
        var reader = new FileReader();
        reader.onload = function (e) {
            document.getElementById('output').src = e.target.result;
        };
        reader.readAsDataURL(file);
    }
</script>

{% endblock %}